spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: password
    url: jdbc:h2:mem:doctor-appointment
    username: sa
  h2:
    console.enabled: true
server:
  port: 8081
  servlet:
    context-path: /api
management:
  endpoints:
    web:
      base-path: /actuator
      exposure.include: health
